const HEADER = "// Do not edit this file; automatically generated by nodejs node_compress_block.js\n 'use strict';\n"
const compile = require('google-closure-compiler-js').compile;   
const fs = require('fs');

js_files_list=['./msg/js/en.js','spin.js','FileSaver.js','base64.js','index_utility.js'];
var jsCodeList2=[];
js_files_list.forEach( function (file){
    if(file.endsWith('.js')){
        var data = fs.readFileSync(file);
        var dataStr=data.toString();    
        jsCodeList2.push({src:dataStr});
    }
});
const flags = {
    jsCode: jsCodeList2,
};
const remove = 'var Blockly={};Blockly.Msg={};'
const out = compile(flags);
var codes = out.compiledCode;
codes = codes.replace(remove,'');
var high_light_js_code=fs.readFileSync('highlight.pack.js').toString();
fs.writeFile('node_compressed_utility.js',HEADER + "\n" + codes+high_light_js_code,function(err)
{
    if (err) {
        return console.error(err);
    }
});