const HEADER = "// Do not edit this file; automatically generated by nodejs node_compress_core.js\n 'use strict';\nvar COMPILED=!0,goog=goog||{};\n"
const compile = require('google-closure-compiler-js').compile;  
const fs = require('fs');
var jsCodeList=[]
var file_list_str = fs.readFileSync('./core_build_list.json');
var file_list_json = JSON.parse(file_list_str)
file_list_json.forEach( function (file){
   if(file.endsWith('.js')){
       var data = fs.readFileSync(file);
       var dataStr=data.toString();    
       jsCodeList.push({src:dataStr});
   }
});
// should we add other compile  flags
const flags = {
jsCode: jsCodeList,
};
//const remove = 'var Blockly={};Blockly.Blocks={};'
const out = compile(flags);
var codes = out.compiledCode;
//codes = codes.replace(remove,'Blockly.Blocks.variables={};Blockly.Blocks.procedures={};');
fs.writeFile('blockly_compressed.js',HEADER + "\n" + codes,function(err)
{
  if (err) {
    return console.error(err);
  }
});
