const HEADER = "// Do not edit this file; automatically generated by nodejs node_compress_generator.js\n 'use strict';\n"
const generator_name = 'mbed'
const compile = require('google-closure-compiler-js').compile;   
const fs = require('fs');
const generator_dir='./generators/'
var jsCodeList=[]
var data = fs.readFileSync(generator_dir+generator_name+'.js');
var dataStr=data.toString();   
jsCodeList.push({src:dataStr});
fs.readdir(generator_dir+generator_name+'/', function(err,files){    
   files.forEach( function (file){     
      var data = fs.readFileSync(generator_dir+generator_name+'/'+file);
      var dataStr=data.toString();    
      jsCodeList.push({src:dataStr});
   });
  const flags = {
    jsCode: jsCodeList,
  };
  const remove = 'var Blockly={};'
  const out = compile(flags);
  //console.log(out.errors);
  var codes = out.compiledCode;
  codes = codes.replace(remove,'');
  fs.writeFile('node_compressed_generator.js',HEADER + "\n" + codes,function(err)
  {
      if (err) {
       return console.error(err);
      }
  });
});
