const HEADER = "// Do not edit this file; automatically generated by nodejs node_compress_block.js\n 'use strict';\n"
const compile = require('google-closure-compiler-js').compile;   
const fs = require('fs');
const blocks_dir='./msg/js/'
var jsCodeList=[]
fs.readdir(blocks_dir, function(err,files){    
   files.forEach( function (file){
       if(file.endsWith('.js')){
           var data = fs.readFileSync(blocks_dir+file);
           var dataStr=data.toString();    
           jsCodeList.push({src:dataStr});
       }
   });
  const flags = {
    jsCode: jsCodeList,
  };
  const remove = 'var Blockly={};Blockly.Msg={};'
  const out = compile(flags);
  var codes = out.compiledCode;
  codes = codes.replace(remove,'');
  fs.writeFile('node_compressed_language.js',HEADER + "\n" + codes,function(err)
  {
      if (err) {
       return console.error(err);
      }
  });
});
